### ISSUE TITLE
How much will the points from the absorb be worth and how big will the discount be in `buyCollateral`?

### ISSUE THREAD

**Issue by egjlmn1** [compound-finance/comet#220]
If there might be a case of a user being alone in the system at the beginning with no initial supply, this user can easily force himself into liquidation and get as many points as he wants.

This can be accomplished like this:
1. I transfer some amount of money to the system, for example, 100$ = 10e8 tokens
2. I supply 1 token to the system, now the utilization is 10e8/1 = 10e8
3. I create many users and borrow a small amount, like 10e4 tokens each, I can do 10,000 of those
4. since the utilization is huge, it won't take long until they are all in liquidation, and then I go over everyone and absorb them

If the points are worth more than the total gas of this attack, I will make a profit.
besides the points I earn from the absorb, the collateral I supplied for the 10,000 users is now on discount, and if I can buy it for less than 100$, that my 10,000 users borrowed, I made a profit

**Comment by jflatow** [comment]
See #420 and #380
