### ISSUE TITLE
[H01] Locked assets in contracts

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#376]
Once the protocol is deployed, the [`Comet`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol) and [`Bulker`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Bulker.sol) contracts will be two important pieces of the system. The `Comet` is the main protocol contract while the `Bulker` is a useful tool to execute multiple protocol calls into one single transaction.

For different purposes, both the `Comet` and the `Bulker` support deposits of ETH into the contract.

In the case of the `Comet` contract, the [delegation](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1347) toward the `CometExt` is in the fallback function, which is declared as `payable`, but there are no parts of both contracts that use them. Moreover, there is no direct way to withdraw any ETH balance present in the contract.

In the case of the `Bulker`, the contract has a [`receive` payable function](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Bulker.sol#L33) to accept ETH which is needed to be used in the `ACTION_WITHDRAW_ETH` according to the [docstrings](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Bulker.sol#L31).
In this case, any ETH sent through the `receive` function will be again lost in the contract, with no possibility to upgrade to a new contract as the `Comet` can. The reason is that the `ACTION_WITHDRAW_ETH` is implemented into the [`withdrawEthTo`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Bulker.sol#L108) function. This function unwraps WETH by sending tokens to the WETH contract and receiving back ETH in the same amount in the `Bulker` contract which are then sent to the user. In this case, the contract's ETH balance will be untouched as only ETH coming from the unwrap will be used.

Lastly, a separate reference must be done also on ERC20 tokens. The `Comet` contract has the [`approveThis`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1294) function which is enough to let a `manager` move any ERC20 fund that might get lost in `Comet` balance. However, this is not the case for the `Bulker` contract, where also ERC20 tokens might get lost.

Consider establishing mechanisms to avoid such scenarios, as it results in a direct loss of user funds.

**Comment by jflatow** [comment]
We added token sweep functionality to Bulker in #413. This required adding an `admin` variable to Bulker as well.
