### ISSUE TITLE
[L01] Everyone can deploy new Comet instances

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#377]
Each [`Comet`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol) contract implementation that the protocol might decide to create is meant to be deployed in the [`Configurator`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol) contract. 

This contract is an intermediate logic to bootstrap the entire protocol configuration and then apply it to a newly deployed `Comet` contract.

To do this, the `Configurator` makes use of a [`CometFactory`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometFactory.sol) contract which has a [`clone`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometFactory.sol#L8) function whose sole role is to create a new `Comet` contract and return its address.

Whenever all protocol parameters are set, the [`deploy`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol#L281) function in the `Configurator` contract is called. This function calls the [`clone`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometFactory.sol#L8) function in the factory and emits an event to signal that a new `Comet` is ready with the configuration set so far.

The `deploy` and `clone` functions are both public callable functions, so anyone can, at any moment, generate the `Comet` instance either in the factory, passing arbitrary configurations, or either through the `Configurator` with the configuration set until that moment.

Is not clear why those functions are public as there is no benefit for users to call them. Moreover, leaving open the door for anyone to deploy instances of `Comet` with arbitrary configuration or emitting arbitrary events through the `Configurator` is a concern to take into account as it might be misused by malicious actors trying to create pishing-like attacks.

Consider restricting access to those functions and let them be called only by the governor or consider properly documenting such a design decision, raising awareness over the way it might be misused.

**Comment by jflatow** [comment]
We considered making `Configurator.deploy()` a governor-only function, however it would require adding a storage slot and complicating the Configurator which does not seem worth the tradeoff. It also doesn’t make sense to change `CometFactory.clone()` to be governor-only as the `CometFactory` is a stateless contract. We note for future reference that there isn’t a great way to get a list of official Comet instances from on-chain, however the canonical repository does have a list (`roots.json`) for each chain, which seems sufficient until a better solution is established.
