### ISSUE TITLE
[L04] Logic contracts initialization allowed

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#378]
The [`Configurator`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol) contract has an initializable function that is meant to be called by the proxy. However, nothing prevents users from directly calling the [`initialize`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol#L46) function on the contract implementantion. If someone does so, the state of the implementation would be initialized to some meaningful value.

We suggest adding a constructor that sets the version to an incredibly high number so that any attempt to call the implementation at the initialize function would revert with an [`AlreadyInitialized`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol#L40) error or even a specific one to signal that initializing the implementation is prohibited.

Leaving an implementation contract not initialized is generally an insecure pattern to follow. In this case, it might lead to a situation where an attacker can take control over the implementation contract by passing himself as `governor` and try to mislead users toward malicious contracts. This is not a security issue on its own but we strongly suggest avoiding such scenarios in all implementation contracts.

As a source of inspiration, [here](https://forum.openzeppelin.com/t/what-does-disableinitializers-function-mean/28730) there's an example of how the scenario can be avoided in general situations.

**Comment by jflatow** [comment]
We made a change to the Configurator constructor to prevent the implementation from being initializable. As for Comet, its current initialize function does not take any parameters and thus is not susceptible to the same risks. Any future changes to the initializer should be carefully reviewed in order to prevent such a vulnerability from being introduced.
