### ISSUE TITLE
[L08] Unnecessary complexity

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#379]
The `Comet` contract [delegates](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1351) some feature implementations into the [`CometExt`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol) contract. This contract is meant to be an actual extension of `Comet` logic and implement some functions and parameters, including the [`version`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol#L22) parameter. 

At the same time, `Comet` is built through an upgradeable proxy pattern that requires a new `Comet` version to be deployed and the proxy pointed toward the new implementation.

Doing an upgrade is convenient to upgrade the version number to a greater value and to do so the protocol must deploy also a new `CometExt` implementation contract to indicate a new version.

This is because the `version` parameter is declared as constant and can't be changed as a result of an upgrade mechanism without actually changing it in the contract's code.

In the worst-case scenario, an error is performed in the upgrade mechanism, the version number is not incremented and potential systems integrated with the protocol might depend on that version number to establish some other logic.

To avoid deploying a new `CometExt` even if its implementation didn't change, consider moving the version parameter into the `Comet` contract code.

Eventually consider keeping `version` in both contracts to differentiate between them, as both contracts might require some implementation changes.

**Comment by jflatow** [comment]
The `version` in `CometExt` is meant specifically as part of the `EIP712Domain` of the contract. Only changes which affect this domain should be reflected in this version. Furthermore the logic relating to the domain is currently isolated to the extension contract, which is useful because it reduces the main contract size, and the size of the main factory.
