### ISSUE TITLE
[L02] Gas inefficiencies

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#388]
There are many places throughout the codebase where changes can be made to improve gas consumption. For example: 

- The `for` loops inside [`absorb`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1158) and [`invoke`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Bulker.sol#L44) functions do not cache the length of the array and perform unnecessary operations on each iteration.
- The `unchecked` blocks for loop counters are not used consistently throughout the codebase. It is only used in the [`Invoke`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Bulker.sol#L63) function, although it could be implemented in loops of the rest of the protocol contracts.
- [updateBasePrincipal](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L816) in `Comet` should not check `principal = 0` because in that case nothing will happen and gas will be wasted.
- It is advisable that if a variable from the contract's storage is going to be read within a function several times, a copy in memory should first be created since reading to the storage directly is expensive. However, if you are only querying for the value once, as in [accrueInternal](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L420-L424) and [`Comet`'s fallback](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1348), it is recommended to read directly from storage without any intermediate steps.
- In `transferCollateral` within the `Comet` contract, it is recommended to consult with [`getAssetInfoByAddress`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1044) at the beginning of the function so that in case the token passed by the parameters is not within the collaterals of the protocol, the function fails early and without wasting gas unnecessarily.
- Use `unchecked { ++i; }` over [`unchecked { i++; }`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Bulker.sol#L63).

When performing these changes, aim to reach an optimal tradeoff between gas optimization and readability. Having a codebase that is easy to understand reduces the chance of errors in the future and improves transparency for the community.

**Comment by jflatow** [comment]
Small gas optimizations made in #419.
