### ISSUE TITLE
[L03] Inconvenient use of `immutable` keyword

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#389]
For accounts that use the protocol, the protocol provides a built-in system for tracking rewards. `Comet` contracts keep account of all accrued incentives for suppliers and borrowers of the base token, and users can claim them on [`CometRewards`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometRewards.sol) contract. It should be emphasized that all rewards from all the `Comet`s from the same chain are claimed in the same `CometRewards` contract.

The latter has a `governor` variable defined which is the role that can set the reward settings and withdraw rewards from the contract. Since the contract does not have an upgradeability mechanism, it is inconvenient to define this variable as [`immutable`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometRewards.sol#L20). If the `governor` needs to be changed, a new contract must be deployed and the old contract's state must be migrated to the new one.

Consider adding this variable to the contract storage and specifying a setter function so that the `governor` can be changed any time it is needed.

**Comment by jflatow** [comment]
We actually already made this change prior to the audit report (#349).
