### ISSUE TITLE
[L05] Missing validations

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#390]
There are some places in the code base that might benefit from some sanity checks on the input provided:

- The [`transferGovernor`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol#L289) and [`setGovernor`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol#L74) functions of the `Configurator` are not checking the address to be non-zero.
- The [`CometRewards`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometRewards.sol#L39) constructor is missing the same check over the address parameter.
- In [line 260](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L260) of the `Comet` contract, the `priceFeed` is set but is not checked to retrieve a valid price.
- [`withdrawAndBorrowAmount`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L672) and [`repayAndSupplyAmount`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L658) functions assume certain values over the `newPrincipal` but those should be required instead.

To reduce possible errors and make the code more rodust, consider adding sanity checks where needed.

**Comment by jflatow** [comment]
In further testing, Kevin found that our assumptions for `withdrawAndBorrowAmount` and `repayAndSupplyAmount` are not in fact statically true, which he has patched here: https://github.com/compound-finance/comet/issues/390
