### ISSUE TITLE
[L07] Underwater accounts can minimize losses

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#392]
In the `Comet` contract, during an [`absorbeInternal`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1173) call, the [`updateBasePrincipal`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1207) function is called, updating the accrued interests on the liquidated user position.

If the seizing of collateral brought the [new user's balance](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1200) to positive values the user will:

- Have his excess collateral exchanged for the base asset (during an absorb this might be beneficial if the collateral price is crashing).
- Have supply interest and tracking indexes accrued straight away after the absorb, over the excess collateral converted into the base asset. Concretely, the `accrueInternal` will update interest rates and the `updateBasePrincipal` will update the tracking indexes.

Moreover, an underwater can decide to even liquidate himself, earning additional liquidation points.

Consider the extra value that an underwater can extract from his position to determine if this can be leveraged to create some attacks. If those are intended behaviors, consider improving the docstrings around the absorption mechanism to reflect these details.

**Comment by jflatow** [comment]
It sounds like the concern is that a user might absorb themselves for liquidator points and to sell off their collateral to the protocol quickly during a market downturn. In that case, it’s the purpose of the collateral factor to ensure a buffer in which the account becomes liquidatable and is still profitable to the protocol to liquidate. If a user chooses to absorb themselves it would economically imply governance has somehow created an absorption incentive greater than the liquidation penalty.
