### ISSUE TITLE
[N01] Anyone can set `baseTrackingIndex`

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#395]
In the `Comet` contract, the [`accrueAccount`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L434) function is publicly callable and it accrues interest rates and updates tracking indexes on the account specified as the input parameter.

Specifically, the tracking indexes are updated in the [`updateBasePrincipal`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L812) function where if `newPrincipal >= 0` then the `baseTrackingIndex` is set to a meaningful value.

So anyone is able to set this value for accounts that do not even exist on the protocol. Even if it is not a security issue on its own, consider restricting this function to users that have a principal strictly greater than zero.

**Comment by jflatow** [comment]
This is intentional so that up-to-date rewards may be accrued by an exterior contract which holds them. Checking for a non-zero principal would increase the gas cost and complexity of the call and should not be necessary. However, we added a test to exercise this code path.
