### ISSUE TITLE
[N02] Inconsistent coding style

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#396]
Inconsistencies in coding style were identified throughout the code base. Some examples are:

- constants variables [`version`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol#L19) and [`name`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol#L22) and not in UPPER_CASE like [other constant variables](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometCore.sol#L26)
- The convention of functions named with the "_" prefix is not clear. Sometimes it is used for [admin functions](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometRewards.sol#L48) and other times for [internal functions](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L241)
- Some structs use [`_reserved`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometStorage.sol#L26) to fill slots, but others do not.
- It is not clear what convention is used for the naming of codebase interfaces. Sometimes the letter [`I`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/IWETH9.sol) is used as a prefix, sometimes the word [`Interface`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometInterface.sol) at the end or in some cases the contract even [misses](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/ERC20.sol) both.

Taking into consideration how much value a consistent coding style adds to the project’s readability, enforcing a standard coding style with help of linter tools such as [Solhint](https://github.com/protofire/solhint) is recommended.

**Comment by jflatow** [comment]
> Inconsistencies in coding style were identified throughout the code base. Some examples are:
> 
> * constants variables [`version`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol#L19) and [`name`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol#L22) and not in UPPER_CASE like [other constant variables](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometCore.sol#L26)]

These exceptional constants exist in order to comply with existing interfaces (ERC20 and EIP-712).

> * The convention of functions named with the "_" prefix is not clear. Sometimes it is used for [admin functions](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometRewards.sol#L48) and other times for [internal functions](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L241)

There are some style differences between contracts which are anyway hard to enforce on-chain, but we removed the “_” prefix in Rewards and renamed “_getPackedAsset” in Comet to “getPackedAssetInternal” to maintain some consistency.

> * Some structs use [`_reserved`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometStorage.sol#L26) to fill slots, but others do not.

This is generally used where we may be using a partial slot that could have some natural uses in the future.

> * It is not clear what convention is used for the naming of codebase interfaces. Sometimes the letter [`I`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/IWETH9.sol) is used as a prefix, sometimes the word [`Interface`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometInterface.sol) at the end or in some cases the contract even [misses](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/ERC20.sol) both.

Some interfaces, such as ERC20, are well known and would be redundant to name as an interface. For Comet, we distinguish the interface using the full word since there is another primary contract with the name Comet. In other cases, such as IWETH9, there is no ambiguity and the prefix letter I is sufficient.
