### ISSUE TITLE
[N03] CometMath is not used consistently

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#397]
Many functions that could be in [`CometMath`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometMath.sol), a utility contract that contains pure mathematical functions, are [scattered throughout the codebase](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometRewards.sol#L139) and [`min`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometMath.sol#L19), one of the functions within the contract, is not being used.

Consider consolidating all the helper math functions in one place and removing unused ones.

**Comment by jflatow** [comment]
CometMath is specifically assumed math for the Comet contract and has changed a fair amount over time. The rewards contract is small and we do not want to add a dependency for a single casting function. 

Thank you for pointing out the vestigial `min` function, we’ve removed that now.
