### ISSUE TITLE
[N05] Incorrect or missing docstrings

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#399]
Across the codebase, some contracts lack proper documentation and docstrings. In particular, the [`IWETH9`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/IWETH9.sol) and [`CometMath`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometMath.sol) functions or the [`CometConfiguration`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometConfiguration.sol) and [`CometStorage`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometStorage.sol) variables are having little comments or nothing at all.

Consider thoroughly documenting all functions and parameters that are part of the contracts' public API. Functions or parameters implementing sensitive functionality, even if not public, should be clearly documented as well. When writing docstrings, consider following the [Ethereum Natural Specification Format](https://solidity.readthedocs.io/en/develop/natspec-format.html) (NatSpec).

Moreover, the `Configurator` contract explicitly states that `BaseToken` and `TrackingIndexScale` [have no setters](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol#L68) but it doesn't specify where those are set, eventually in the `config` parameter [passed as input in the `Configurator` initialization](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol#L46).

Consider writing this in the docstrings of the `initialize` function to improve clarity.

**Comment by jflatow** [comment]
We strive to have good documentation on the interfaces of the protocol. We do not seek to document every internal function in every contract touched by the protocol but we welcome the specific suggestions.  We added documentation to the `initialize` function of the `Configurator`.
