### ISSUE TITLE
[N06] Lack of indexed parameters

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#400]
The [`CometDeployed`, `GovernorTransferred`, `SetFactory`, `SetGovernor`, `SetPauseGuardian`, `SetBaseTokenPriceFeed`, `SetExtensionsDelegate`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Configurator.sol#L13-L19) events lack of any indexed parameter.

Consider [indexing event parameters](https://solidity.readthedocs.io/en/latest/contracts.html#events) to avoid hindering the task of off-chain services searching and filtering for specific events.

**Comment by jflatow** [comment]
We agree that these event parameters can be `indexed` to facilitate off-chain processing and have made the change.
