### ISSUE TITLE
[N07] Contracts folder is not properly organized

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#401]
There is no convenient structure in the [`contracts` folder](https://github.com/compound-finance/comet/tree/0f1221967149115f50a09681eea9580879ee7720/contracts) to easily navigate between them. All contracts, regardless of their type or module they belong to, are mixed in a single folder.

To favor the developer experience and the maintenance of the codebase, consider adding additional folders following the structure within the `vendor` directory or separating protocol components into different internal folders.

**Comment by jflatow** [comment]
The code actually is logically organized in that the protocol code sits at the top-level, with test and vendored contracts being secondary and sitting in subdirectories.
 
In the future we may reorganize to something like the following, however not at this time:
 - `configurator/`
  Configurator-related contracts
 - `protocol/`
  Core Comet-related contracts
 - `proxies/`
  Proxy-related contracts
 - `supplemental/`
  Rewards, Bulker, any other supplementary contracts that are non-core
