### ISSUE TITLE
[N08] `rewardsClaimed` can be mixed between different tokens

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#402]
In `CometRewards` it is possible to change the reward token of each `Comet` through [`_setRewardConfig`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometRewards.sol#L48). However, if the reward token is changed, the number of previous reward tokens claimed will persist and once someone claims their new reward asset, it will be added to `rewardsClaimed` despite being different assets.

Consider removing the ability to change the reward asset once set or changing the way the claimed rewards are stored if the reward asset changes.

**Comment by jflatow** [comment]
We’ve made the change to only allow setting the rewards token if it’s not been set and prevent the unlikely misconfiguration.
