### ISSUE TITLE
[N09] Naming issues

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#403]
To favor explicitness and readability, several parts of the contracts may benefit from better naming. Here are some examples:

- The name [`CometProxyAdmin`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometProxyAdmin.sol) suggests that it is only the admin of the Comet proxy, but in reality, it will also have the same role on the `Configurator` proxy. Choose another name to avoid confusion.
- [`TransparentUpgradeableConfiguratorProxy`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/TransparentUpgradeableConfiguratorProxy.sol) can be called `ConfiguratorProxy`. There is no need to use the inherited contract name as a prefix.
- In `CometMath`, change [`InvalidUInt`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometMath.sol#L12-L14) to `InvalidUint` and [`toUInt`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometMath.sol#L58) to `toUint`.
- [`rescale`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L353) and [`descale`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L269) have different names but the same value, consider using one variable name `scale`.

**Comment by jflatow** [comment]
There are some good points made about the chosen names, however naming is a notoriously hard problem and we believe it is difficult if not impossible to make everyone happy. We adopted some of the proposed changes in #433.
