### ISSUE TITLE
[N10] Use of Global imports

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#404]
Non-explicit imports are used throughout all protocol contracts, which reduces code readability and could lead to conflicts between names defined locally and the ones imported.

The inheritance chains within the protocol are long, and for this, the codebase would benefit from refactoring specifically which definitions are being imported in each contract.

On the principle that clearer code is better code, consider using named import syntax *(`import {A, B, C} from "X"`)* to explicitly declare which contracts are being imported.

**Comment by jflatow** [comment]
We do not consider this important or worth the effort of refactoring at this time.
