### ISSUE TITLE
[N11] Potential front-run

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#405]
The [`deployAndUpgrade`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometProxyAdmin.sol#L16) function of the `CometProxyAdmin` is restricted in access to be called exclusively by the governance. It deploys a new `Comet` instance through the `Configurator` and upgrades the implementation address in the proxy.

However, it doesn't call the [`initializeStorage`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L225) function of the `Comet` contract through the proxy, leaving the new implementation not initialized. The function doesn't take any input parameter and it is meant to be called only once without the need to call it again on new implementation upgrades.

Whether the first initialization is performed on a separate transaction or if in the future it will be possible to re-initialize the `Comet` instance with some input values, any user can front-run any governance attempt to initialize the new deployed `Comet`.

Consider taking into account that `deployAndUpgrade` and `initializeStorage` should be done in one unique transaction to avoid the front-run scenario, especially if input parameters or re-initializations are meant to happen in future developments.

**Comment by jflatow** [comment]
Since upgrades will always be done via governance proposals, newly introduced `initialize` functions should always be called within the same governance proposal as the upgrade. We built a scenario to test this use case.
