### ISSUE TITLE
[N13] Repetitive code

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#407]
In many parts of the codebase, repeated or similar lines of code can be seen. Here are some examples:

- In Comet, lines [520-525](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L520-L525), [555-561](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L555-L561), [593-598](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L593-L598) and [628-634](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L628-L634) are repeated and loops after those sections have strong similarities.
- `timeElapsed > 0` check is performed two times, when [accrueInternal](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L414) is called, and when internally [accruedInterestIndices](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L399) is called.
- [`allow`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol#L149) and [`approve`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol#L120) in `CometExt` do the same thing.

Consider reusing the same code defined in just one place or, if appropriate, removing duplicate code.

**Comment by jflatow** [comment]
We gave considerable thought to how redundant sections of the code were organized and tried various permutations. Although seemingly redundant, the current form is overall the best we found in terms of the properties we were evaluating (namely clarity, code size, gas cost).
