### ISSUE TITLE
[N15] Unnecessary return values

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#409]
In the `Comet` contract, there are functions like the [`supply`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L854) or [`withdraw`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/Comet.sol#L1059) that return calls to internal functions even if there's no actual final value returned at the end.

Consider reviewing all the occurrences where this happens and avoid returning when not necessary. This will improve readability and correctness.

**Comment by jflatow** [comment]
These are used to handoff control flow and can actually improve readability with that understanding.
