### ISSUE TITLE
[N17] `PRICE_SCALE` constant is not used

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#411]
A constant called [`PRICE_SCALE`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometCore.sol#L55) is defined in the `CometCore` contract and is supposed to be used to scale the prices returned by Chainlink aggregators.

Although the function [`priceScale`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometExt.sol#L54) returns the value stored in the bytecode, the constant is not used anywhere else.

Consider removing this constant or alternatively integrating it into the codebase.

**Comment by jflatow** [comment]
The `PRICE_SCALE` is derived from the `PRICE_FEED_DECIMALS`, which is internal, but exposed to the public via `priceScale`. `PRICE_FEED_DECIMALS` is used in the constructor checks and `PRICE_SCALE` is referenced in the docs.
