### ISSUE TITLE
pauseGuardianSigner is null

### ISSUE THREAD

**Issue by zjb0807** [compound-finance/comet#483]
https://github.com/compound-finance/comet/blob/ad6a4205a96be36417632afba2417f25b6d574ad/src/deploy/Development.ts#L71

If use `ETH_PK` in .env, the pauseGuardianSigner will be null

**Comment by jflatow** [comment]
This should be patched by https://github.com/compound-finance/comet/commit/72c67df92193ac2f6d1a9c7ed4307b3608211980
